# Generated by Django 4.2.10 on 2024-02-23 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_profile_options_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیام')),
                ('edit', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر ')),
                ('text', models.TextField()),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت کننده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='کاربر فرستنده')),
            ],
            options={
                'verbose_name_plural': 'پیام های فرستاده شده ',
                'db_table': 'TextToText',
            },
        ),
    ]
