# Generated by Django 4.2.10 on 2024-02-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextToText',
        ),
    ]
