# Generated by Django 4.2.10 on 2024-02-23 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_profile_options_profile_first_name_and_more'),
        ('Message', '0002_delete_texttotext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riciver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='کاربر دریافت کننده')),
            ],
            options={
                'verbose_name_plural': 'دریافت کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='کاربر فرستنده')),
            ],
            options={
                'verbose_name_plural': 'ارسال کنندگان',
            },
        ),
        migrations.CreateModel(
            name='TextToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پیام')),
                ('edit', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر ')),
                ('text', models.TextField()),
                ('reciver1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Message.riciver', verbose_name='کاربر دریافت کننده')),
                ('sender1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Message.sender', verbose_name='کاربر فرستنده')),
            ],
            options={
                'verbose_name_plural': 'پیام های فرستاده شده ',
                'db_table': 'TextToText',
            },
        ),
    ]
