# Generated by Django 4.2.10 on 2024-02-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options_profile_first_name_and_more'),
        ('Message', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Riciver',
            new_name='Reciver',
        ),
    ]
