# Generated by Django 4.2.10 on 2024-02-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options_profile_first_name_and_more'),
        ('Message', '0005_alter_texttotext_reciver1_alter_texttotext_sender1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttotext',
            name='reciver1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='account.profile', verbose_name='کاربر دریافت کننده'),
        ),
        migrations.AlterField(
            model_name='texttotext',
            name='sender1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='account.profile', verbose_name='کاربر فرستنده'),
        ),
    ]
