# Generated by Django 4.2.10 on 2024-02-24 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Message', '0006_alter_texttotext_reciver1_alter_texttotext_sender1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttotext',
            name='reciver1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت کننده'),
        ),
        migrations.AlterField(
            model_name='texttotext',
            name='sender1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر فرستنده'),
        ),
    ]
